### ISSUE TITLE
Add a Cron schedule to app

### ISSUE THREAD

**Issue by agusalex** [agusalex/grive2Docker#5]
Make it possible for grive to start at a scheduled time. This should replace the sleep feature.

**Comment by agusalex** [comment]
@victorkp hey what do you think? I can make that happen but was wondering if the Sleep feature would make any sense when having something as powerful as a Cron schedule available. By setting Cron to * * * * * I can make it run every minute, maybe it loses some granularity that the sleep feature had. But we can always keep them both dunno.

**Comment by victorkp** [comment]
Cron would be an improvement in my book! I had only implemented the SLEEP
variable out of convenience.

**Comment by agusalex** [comment]
Perfect, I'll get that working since other people had asked for that feature and it shouldn't take that long

**Comment by agusalex** [comment]
Well this is now complete Crontabs now supported, took some time but we got there!
